### ISSUE TITLE
Life-cycle of the recurrent layer

### ISSUE THREAD

**Issue by TayBoshin** [andreyzharkov/keras-monotonic-attention#11]
Hi Andrey,
and first of all, thank you very much for your hard work! I was very happy that you confirmed that the implementation of the attention mechanism by Zafarali Ahmed was indeed missing the teacher forcing.
I am relatively new to python / keras and was trying to get a grasp of the life-cyle of this recurrent layer, i.e. which function is when and how often called. I kindly request your help, since you have so intensively worked with it. I am trying to set my question in context to your attention_decoder.py code.
**Procedure (Life-cycle)**
So, suppose I have the following example input sequence
`seq_in = np.arange(4).reshape( (1,4,1) )`
So, `seq_in` is the sequence 0, 1, 2, 3
I got the following idea for one recurrent cell
1.  `build(self, input_shape=(1,4,1) )`
is called when I build the model. All relevant weight matrices are initialized.
2.	`call(self, x)`
is called when I build and compile the model.
3.	`get_initial_state(self, inputs)`
is called twice in` call(self, x)`.

**Questions**
So according to the logic of recurrent networks, I assume the sequence is step by step fed to the cell. Meaning, first 0 is fed, than 1, than 2, and finally 3.
My first question: Is the `step(self, x, states)` called 4 times for each step of the sequence? 
This implies that x is one tensor with shape (batch_size, 1, n_features) with fixed time step of 1. Correct?
The function `step(self, x, states)` returns 2 arguments.
`return output, next_states`
Is it correct, that the `next_states` are fed into `step(self, x, states)` via states and the output not?

If that is correct and I now try to use 2 input sequences, e.g. one from an encoder and the ground truth values in order to apply teacher forcing, I would assume that x now consists of two tensors with the shapes (batch_size, 1, n_features_encoder) and (batch_size, 1, n_features) for the `step(self, x, states)` function.
So, this code line within the `step(self, x, states)` function
`xt, truth = x`
should allow me to access the relevant ground truth for each time step. With this I could discard your approach with the index `timestep` accessing the` self.y_seq`. However, I have to drop xt since the math behind the attention GRU requires the whole sequence, which is stored in the cell by` self.x_seq`.

Of course, I preprocess the data for the ground truth so that it is offset by one step, so I don’t have to worry about time indices in step.
Hopefully, I could point out my problem.

**Additional**
For what do we need
Line 333-337?
```
last_output, outputs, states = K.rnn(
            self.step,
            inputs=fake_input,
            initial_states=self.get_initial_state(self.x_seq)
        )
        return outputs

```

**Comment by reyzharkov** [comment]
Hi Tay,

Your understanding of how RNN work is quite correct. Assuming recurrent layer has input x of shape (batch, time, n_features) it is firstly fed into call. 
```python
def call(self, x):
  # x has shape (batch, time, n_features)
  states = self.get_initial_states(x)
  outputs = []
  for i in range(time):
    output, states = self.step(x[:, i, :], states)
    outputs.append(output)
  return np.stack(outputs, axis=1)  # (batch, time, m_features)
```
(The code above is more like pseudocode and won't work, but gets an idea of an order of calling methods.)

To your additional question - lines with K.rnn do this pseudocode for cycle.
The problem with keras is that it (one of the base recurrent layers) assumes that `x` fed into `step` is a single tensor and not a list of tensors (in that case it will do something like `x, states = x[0], x[1:]`). So to avoid this I had to override the `call` method.

About discarding `timestep` and using aligned input instead of it you are also right - instead of passing `fake_input` to rnn you may pass `y_true`, then on each timestep `step(x, states)` you will get `y_true[:, time, :] == x`

**Comment by TayBoshin** [comment]
Thank you very much for your help!
